[package]
name = "minizinc-diff"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
rand = "0.9.2"
shell-words = "1.1.0"
